### Alacritty - TOML configuration file format


### GENERAL
### This section documents the root level of the configuration file
# All imports must either be absolute paths starting with `/`,
# or paths relative to the user's home directory starting with `~/`
[general]
import = []
working_directory = "None"
live_config_reload = true


### ENV
### Any items in the `env` entry below will be added as
### environment variables. Some entries may override variables
### set by alacritty itself.

### WINDOW
### This section documents the [window] table of the configuration file
[window]
dimensions = { columns = 120, lines = 50 }
padding = { x = 0, y = 0 }
opacity = 1.0
startup_mode = "Windowed"
title = "Alacritty"


### SCROLLING
### This section documents the [scrolling] table of the configuration file
[scrolling]
history = 10000


### FONT
### This section documents the [font] table of the configuration file
[font]
normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }
size = 12.0


### KEYBOARD
### This section documents the [keyboard] table of the configuration file
[keyboard]
bindings = [
    # `Ctrl+Ins` for "Copy"
    { key = "Insert", mods = "Control", action = "Copy" },
    { key = "Insert", mods = "Control", mode = "Vi|~Search", action = "ClearSelection" },
]


### COLORS
### This section documents the [colors] table of the configuration file
[colors]

# Tokyo Night
[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"
[colors.normal]
black   = "#15161e"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#a9b1d6"
[colors.bright]
black   = "#414868"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#c0caf5"
[[colors.indexed_colors]]
index = 16
color = "#ff9e64"
[[colors.indexed_colors]]
index = 17
color = "#db4b4b"
